version: '3'
services:
  app:
    image: golang:latest
    container_name: go_container
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/go
    depends_on:
      - db

  db:
    build: ./docker/mysql
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: go_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3314:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql